PKGS=python-pynvim ripgrep

PYTHON = python-lsp-server python-pycodestyle python-mccabe python-pydocstyle python-pyflakes python-pylint python-rope flake8 yapf python-whatthepatch autopep8 python-isort python-black mypy
JAVASCRIPT = 
TYPESCRIPT = typescript-language-server
BASH = bash-language-server shfmt shellcheck shellharden
C = clang cppcheck
LUA = stylua
GO = gopls
OTHER = prettier yamllint codespell ansible-lint cmake-language-server dockerfile-language-server vscode-html-languageserver vscode-json-languageserver texlab sqls lemminx

# Add qmlls, awk language server and ansible language server, markdown lint (decide package), vscode-markdown-languageserver after packaged

external:
	# External packages required by neovim
	paru -Syu $(PYTHON) $(BASH) $(C) $(LUA) $(OTHER)


## install lsp's
## download extra packages

## start up nvim in headless to install plugins

## init config
