# .zshenv is sourced on all invoations of the shell, except when -f is set.
# It should contain commands to set command search path and other important
# environemnt variables.
# It should not contain any commands that produce output or assume the shell
# is connected to a tty

# Export XDG Base Directory spec in case it isn't set
export XDG_CONFIG_HOME=${HOME}/.config
source ${HOME}/.config/user-dirs.dirs

export LC_ALL="en_US.UTF-8"

# Export ZDOTDIR for easy configuration
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
export SUSPENDED_JOBS

# Export my local scripts to CONFIG_HOME
# Note: probably not the right place to stick these, but it allows for
# a more portable bootstrapping script
export PATH=$XDG_CONFIG_HOME/bin:$PATH

# add local bins
export PATH=$HOME/.local/bin:$PATH

## My docker shit
export DOMAIN=jdb314.duckdns.org
export DOCKER_DIR=/data/vms/docker
export DUCKDNS_TOKEN=c8646cea-9d1b-4dbd-bbf5-dbb6246cd38d

# SSH agent variables
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    export MOZ_ENABLE_WAYLAND=1
fi
