install:
	# link the whole directory to config to load environment variables with systemd
	# Note: this will make environment variables available to all shells
	ln -sfv ${PWD} ${XDG_CONFIG_HOME}/environment.d
